### ISSUE TITLE
Точки для презентации

### ISSUE THREAD

**Issue by abitrolly** [minsk-hackerspace/api.nbrb.by#9]

**Comment by abitrolly** [comment]
#7 Банк API для Интернета вещей

Мы придумали и реализовали протокол autodiscovery для того, чтобы устройства и приложения могли автоматически находить сервисы, предлагаемые банками, и предлагать пользователю их настроить.

Разработчикам не надо отдельно писать интеграцию для каждого из 26 банков, не надо вбивать список сервисов и обновлять приложение под каждый банк. Как только банк реализует сервис, приложение автоматом его подхватывает. Пользователю не надо заключать дополнительные договора. Со стороны банка надо только выставить ограничения на конкретный API и сообщить приложению ключ. Синхронизация ключа происходит автоматически.

**Comment by abitrolly** [comment]
Спецификация открытого API для нац.банка РБ.
1. Получение списка банков
2. Получение списка банкоматов

**Comment by abitrolly** [comment]
Спецификация открытого API для финансового института:

1. Получение счетов
2. Получение баланса счёта

**Comment by abitrolly** [comment]
Хватит писать парсеры - пора развивать экосистему.

**Comment by chertby** [comment]
Ссылка на тесты http://joxi.ru/V2VaQ3PHxGBK4m

**Comment by chertby** [comment]
Небольшое [видео](https://www.dropbox.com/s/ex2ady35kkmqvap/Open%20FinTech%20API.mp4?dl=0)

**Comment by chertby** [comment]
http://joxi.ru/5md0jBPFkJqOjm новый принт скрин

**Comment by abitrolly** [comment]
Погибнет оно там. Надо перезаливать сюда.

![6ece49beac](https://cloud.githubusercontent.com/assets/8781107/25991802/48e85bb4-370d-11e7-8500-69aa3195d82e.jpg)

![7595fc1da4](https://cloud.githubusercontent.com/assets/8781107/25991821/5cd82244-370d-11e7-93dd-5f6c04e861a9.jpg)

**Comment by abitrolly** [comment]
[Open FinTech API.mp4.zip](https://github.com/minsk-hackerspace/api.nbrb.by/files/995620/Open.FinTech.API.mp4.zip)

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/8781107/25992088/3017b476-370e-11e7-9dbd-8c8418fe6647.gif)
